import java.util.Arrays;

public class BurrowsWheelerTransform {

	public static void main(String[] args) {
		String text = "ACAGCGAAGGCAGTGTCTGTTTCGTGCCCACATTCCTGGATTCAGCTATTCTCTTTTACCGATAGGTATGGCATAGTATCTGCTTTTATTAAGAGCTGCAGATGTTTGGTAATTCTTGGACAGCTGAACCCTACGCGCAGCTCGAAAGCGTCAACACGAGACTCCTTTCGTCTAGCAGTCAAAGTGTACTGATGCTCTACGTACTTATGACCAGCCTATCCGTAGGCGGCCAAGGAAATTAACGGAAACAGGTCGGGGTAAGAAACACGCTTGATCCTCACTGGTCTTGTAAGATGGATACCCGTGGGGACTTCTATTTGTCGAGCACTTCGACTAAGCTATGACCTACTCATGATTTCGTATCGCAAGTCTCCGACCCCCGACATGTGATGGAATATCTAGGAGCGTAAGGACCATTGGTCCAAGCCGCACATACTAACGCATCTTCTGTCGCGAATCCAGCTTGTCCTATAAATATAAGGGGCGAGCATTAGATTCTCTGATCCGTCAGTCCGTACCTAAGCTAAAATCCAAACATGTTAGTACTGAGCGGAATTTGGACTCACCTCCTCTTGTGGTACTCTCATTAGACTCATATTCCCTTAACTACGGGTATGATATTAGAGGACTCTCCTGTGATTCTTAATGTGAAGGCTTCTAAGTACGGCTGGACCGGTCATCACAATAAATACAACCCTTACCAGTCTGGCGAATCATTCTTTGCGTTACCGACAACGGGACTCGTGTGGTGCAGGTTAGCACCGTCTGCTCACCAGTGAAAGGATATTTTCAGGCTAGATAGTTGTATTTTTGTACCGCGAGTACACCAGGCCCCGTCCAACCTGAACCCTATTCATGACGCCGTGGACTCGGGGT$";
		System.out.println(bwt(text));

	}
	public static String bwt(String s) {
		String[] matrix = rotationMatrix(s);
		String bwt = "";
		for (int i = 0; i < matrix.length; ++i) {
			bwt += matrix[i].charAt(s.length() - 1);
		}
		return bwt;
	}
	public static String[] rotationMatrix(String s) {
		String[] matrix = new String[s.length()];
		for (int i = 0; i < matrix.length; ++i) {
			matrix[i] = s.substring(i, s.length()) + s.substring(0, i);
		}
		Arrays.sort(matrix);
		return matrix;
	}

}
